Repository proroklab/VectorizedMultiAgentSimulator, pull requests merged in 2024-09, with the labels that each got.

#139 [Bug fix] Navigation scenario: ensure entity placement within constrained environment boundaries
  vmas/scenarios/navigation.py
Labels: bug

#142 [Feature] Boundary visualization for limited-size environments
  vmas/scenarios/balance.py
  vmas/scenarios/ball_passage.py
  vmas/scenarios/football.py
  vmas/scenarios/joint_passage.py
  vmas/scenarios/joint_passage_size.py
  vmas/scenarios/mpe/simple_tag.py
  vmas/scenarios/passage.py
  vmas/scenarios/road_traffic.py
  vmas/scenarios/sampling.py
  vmas/simulator/environment/environment.py
  vmas/simulator/scenario.py
Labels: enhancement

#143 [Feature] Terminated/truncated support and Gymnasium wrapper
  .github/unittest/install_dependencies.sh
  README.md
  docs/source/conf.py
  docs/source/usage/installation.rst
  setup.py
  tests/test_vmas.py
  tests/test_wrappers/__init__.py
  tests/test_wrappers/test_gym_wrapper.py
  tests/test_wrappers/test_gymnasium_vec_wrapper.py
  tests/test_wrappers/test_gymnasium_wrapper.py
  vmas/interactive_rendering.py
  vmas/make_env.py
  vmas/simulator/environment/__init__.py
  vmas/simulator/environment/environment.py
  vmas/simulator/environment/gym.py
  vmas/simulator/environment/gym/__init__.py
  vmas/simulator/environment/gym/base.py
  vmas/simulator/environment/gym/gym.py
  vmas/simulator/environment/gym/gymnasium.py
  vmas/simulator/environment/gym/gymnasium_vec.py
  vmas/simulator/environment/rllib.py
Labels: enhancement, bc-breaking
